# Generated by Django 3.2.25 on 2025-10-25 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='date',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_airport',
            field=models.CharField(default='Unknown Airport', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_airport',
            field=models.CharField(default='Unknown Airport', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='flight',
            name='seats_available',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('On-time', 'On-time'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled')], default='On-time', max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_booked', models.PositiveIntegerField(default=1)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
