# Generated by Django 3.2.25 on 2025-10-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', help_text='Admin approval status for the user.', max_length=10),
        ),
    ]
